### ISSUE TITLE
How to deal with the images with shapes  of odd number? 

### ISSUE THREAD

**Issue by wl082013** [zhaoyuzhi/Self-Guided-Network-for-Fast-Image-Denoising#4]
Hi, 
I encountered some errors when training the network using my data.
In the training phase, I resized the images to a certain size (eg. 256), and in the invalidation phase, I did not resize since I want to keep the original image size. However,  it turned out the pixel_unshuffle can only work with images with shapes of odd numbers. For instance,  if I have an original image with a height of 134, after pixel_unshuffling once, it became  67, and then became 33,  etc. But when it is shuffled, it became 66 and 132, which is different from 67 and 134, thus making cat(x2, x1) and cat (x1,x) impossible. So is there any good way to cope with this case?

**Comment by zhaoyuzhi** [comment]
There is no best way to address this problem. An alternative way is to crop your big image firstly, and then feed the patches into network. Finally, concatenate all the generated patches to obtain original resolution.

**Comment by wl082013** [comment]
> There is no best way to address this problem. An alternative way is to crop your big image firstly, and then feed the patches into network. Finally, concatenate all the generated patches to obtain original resolution.

Okay thanks for your quick help.
I am wondering about resizing the tensor of e.g. 66 to 67 to match the original tensor shape, but I am not sure whether it is okay to do it in this way.  How did you deal with the training and test data in your case? did you resize all images to a certain size?  Thanks for your help.

**Comment by zhaoyuzhi** [comment]
I think it may be not feasible to resize tensor. For big images, cropping is helpful. In practice, you may extract overlapped patches to avoid border effect

**Comment by wl082013** [comment]
> I think it may be not feasible to resize tensor. For big images, cropping is helpful. In practice, you may extract overlapped patches to avoid border effect

Okay thanks for your help.
